### PR TITLE
Move D2BotPubJoin.dbj to main branch.

### PR DESCRIPTION
**Pull request by StoneOfJordan**
Features:
- Will join a public game using the game list.

Spam bots are dead anyways.

### CODE REVIEW

**Comment by noah-** [comment]
Has this script been tested properly?

**Comment by StoneOfJordan** [comment]
It passed all of my debug tests, that however happened a while ago.

**Comment by noah-** [comment]
Can you share what type of testing you conducted?

**Comment by StoneOfJordan** [comment]
Some basic functionality tests:
- Join game(s) listed in include list
- Ignore game(s) listed in exclude list
- Ignore games that it already joined
- Change sequence in case of FTJ

Those are the relevant ones that I can remember. Maybe someone else can test it properly.

**Comment by noah-** [comment]
Added.

**Pull request closed without merging**
