### PR TITLE
show IP of the game

### PR DESCRIPTION
**Pull request by mf022**
Show IP of the game in manager's <Status> column for D2BotLead, D2BotFollow and D2BotChannel starter scripts.

### CODE REVIEW

**Comment by noah-** [comment]
what's the purpose of showing the IP unless IP hunting?

**Comment by mf022** [comment]
maybe the same of MapThread.js where that addition was used by default.
Some people wanna see faster the IP when they saw messages about DClone to start IP hunting, instead running netstat every time.

**Comment by jaenster** [comment]
Maybe instead of always showing maybe it can log it to D2Bot console? (with ip?)

**Comment by mf022** [comment]
closed

**Pull request closed without merging**
