### PR TITLE
(WIP) Fix areachange #259

### LINKED ISSUE #258: Connection interrupted when opening doors
After blizz server restart on 8/22, when using autotele or bot to teleport to an area with a closed door, you will get 'Your connection has been interrupted' when opening the door. It seems to happen on all accounts and all characters (not account or class specific)
Example areas:
ruined fane, ancient tunnels

### PR DESCRIPTION
**Pull request by coldstorage**
fixes #258
alternative to #259

### CODE REVIEW

**Comment by StoneOfJordan** [comment]
The version that I submitted still has some issues that I didn't take into consideration, I'll submit an updated & cleaner version in a bit.

**Comment by noah-** [comment]
I'll leave the same comment I told StoneOfJordan,
http://codepad.cf/#openExit

I think a lot of the added functions are somewhat unnecessary.

**Comment by coldstorage** [comment]
Just to clarify. You think the added code hould just open the exit, and let existing code walk through it afterwards?

I think that doesn´t work. existing code interacts with these type5 units. but interacting with em, even after opening the correspoinding type2 units still gives a disconnect. i just gave it a quick try in luth.

i will take a further look tonight and report back.

**Comment by coldstorage** [comment]
nvm overread the unit.interact() in line 22 of your code...

your example is oversimplified and will not work. there are exits where you have to pull a lever and enter an exit afterwards. these are two different units.

* getSpecialExitInfo - i think there is no way around something like this.
* takeSpecialExit -actually helps against code duplication
* sendInteractPacket - enforce do not repeat yourself idiom
* waitTillExitOpen - better than a simple dealy also avaoids code duplication
* waitForAreaChange - same as above + it is extracted from useUnit so it is not even added code

anyway, i will take a look, if i can simplify it a bit

**Comment by noah-** [comment]
I actually agree with a lot of what you are saying. However, to reduce code duplication, I think more generalized functions should be introduced, and this is not just a comment on your code but on kolbot code in general. For example, the open seal code is actually very similar to what the lever code should be. Doing getUnit in a loop should be abstracted out to a getUnitEx that uses a timeout input. If we look through kolbot, I'm sure there are various areas that can benefit from this type of refactoring.

**Comment by coldstorage** [comment]
thanks for the comment. i agree with you.
closing, as you already committed another fix

**Pull request closed without merging**
