### PR TITLE
Mandatory Bosses feature added; New features for bot scripts added

### PR DESCRIPTION
**Pull request by Nishimura-Katsuo**

### CODE REVIEW

**Comment by Nishimura-Katsuo** [comment]
I'll reopen later. Going to rework a little.

**Comment by Schmeden** [comment]
Hi,

I modified this feature slighly since it didn't work properly for me, now it telestomps mandatory bosses.
My local script-lib is so modified that I CBA to create a pull-req. 

How:
- Do a function in Sorceress.js that checks if it´s mandator (such as isMandatory), with the code you already created, make it take unit as input.
- on the Telestomp-part, (case2 around row 117), change to if (Config.TeleStomp || this.isMandatory(unit))..

Then it will telestomp the mandatory bosses, works best if bossprio in char-config is false so it doesn´t telestomp into fana right away. I got zero chickens/dia not found for about 200 runs.

My two cents for a pull-req-worthy feature:
The logic should probably be put somewhere else, and perhaps encapsulated into a config-variable such as: TeleStompChaosBosses true/false (perhaps baal-minions too). This because having getlocalestring with magic numbers is not so user-friendly :)

**Comment by MrUndercover** [comment]
Hi, I modified your feature slighly to make it work, it was skipping with the code you provided. CBA to do a PR since my lib is so modified.

**How (changes in Sorceress.js):**
- Put your code to check if mandatory in a function
- Change telestomp to if(Config.Telestom || this.isMandatory(unit)...
- Config remains the same in char.config.

I got 200 runs with 0 diablo-not-found since this change.

**Idea to make it a good userfriendly feature:**
Make a configvar "TryTeleStompMinions" and encapsulate all locale-strings for monsters, so people don´t have to worry about em.

**Comment by Nishimura-Katsuo** [comment]
Changing it to:

  Config.TeleStomp || this.isMandatory(unit)

That would make it telestomp bosses even if telestomp is set to false, yes? It should adhere to that config option consistantly otherwise it would run into unexpected behavior for people that absolutely do not want to telestomp.

Good thought on making it a separate function, but it's already just an index lookup with no extra logic so it didn't seem needed.

The feature was intended for bosses that you don't want to skip; not just chaos bosses. My blizzard sorc would skip pindleskin even though it's an easy kill just because it was cold immune. I should definately clarify that you can specify names just by typing "Pindleskin" too, not just with magic numbers.

I use a ton of custom features that I haven't submitted as a PR so feel free to keep using your own modifications :)
________________________________

**Comment by MrUndercover** [comment]
Yeah exactly. I use it mainly for Lord de seis (sorc is cold/light spec), and like it as an override to the telestomp, since it's the only way my char can kill those specific resists, while I still don't want to telestomp Death-lords for example, my sorc would die trying.

I agree that my take on this feature should be named something like "ForceTeleStomp". Also thanks for the info that strings can be used, dunno why I didn't try that.

I should start contributing, it´s a very good project, nicely documented and such!

**Pull request closed without merging**
