### PR TITLE
SpeedBaal. An optimized Baalrun that tries to run as fast as possible.

### PR DESCRIPTION
**Pull request by jaenster**
First of all, this isn't designed for a mf run, pure fast baal for xp.

Highlights,
1) Faster clearing of the throne by only killing the necessary monsters for a wave to spawn
2) Lighting / Blizzard / Meteor / Hammers / Fury, and many more skills are cast just on time before wave comes. To save mana, but also to have maximum impact
3) Added some custom pickit lines to avoid NPC interactions, to make runs go faster. (again this isn't an mf run, its an xp run)
4) Overrides Attack.clear function to be quicker better for the throne, but don't worry after the script is done (or crashed), it puts the original clear script back.

### CODE REVIEW

**Comment by Nishimura-Katsuo** [comment]
Needs reformatting to be consistent with kolbot's current formatting(noah is strict about this):
- 1 tab instead of spaces for indentation
- utf-8 formatting was dropped and needs to be fixed (also \xFF is ÿ with utf-8)
- needs empty line between blocks and other statements (if, switch, for, while, etc), and empty line before break/return statements, empty lines as the first/last line of a block needs removed

Are you trying to thread the script? I think this can be done in a more straight forward way without threading.
What is wrong with the attack code in Attack.js? If you want to make custom builds, perhaps you should save the attacks in Config.AttackSkill, overwrite them, and then restore them after the script is done (in the case this is not the last script). Or perhaps redefine key functions instead of recoding the entire attack process (as Attack.js gains changes to make it better your script will not gain those advantages).

**Comment by jaenster** [comment]
@Nishimura-Katsuo 

- Fixed the 1 tab over spaces indentation.
- The utf-8 formatting might been dropped, but [this commit](https://github.com/kolton/d2bot-with-kolbot/commit/d46067ff25458ce2c443dd92b467a18ab34721c7) changed all the ÿ's to \xFF. Thus i didnt alter it in the last commit. Also, my IDE really dislike the ÿ and im not [alone ](https://github.com/kolton/d2bot-with-kolbot/pull/520)in this
- I set my IDE to those rules now, it automatically formatted correctly and it will in the future.

About the thread, yeah i think that is an mistake indeed. I wanted to add some communication between the currently running scripts. I'll add that, so please don't merge it yet. I'm limited in the time i can code on it sadly, but i might just remove the entire thread.

About the Attack code in Attack.js and ClassAttack.js, its fine, but some custom stuff is designed for the throne, and will not be preferable behavior for outside the throne. To take the javelin skills as example, you simply don't want to preform that many fury's outside the baalrun. Its impossible to add conditions on the Config.AttackSkills. The Attack.clear function i overwrite (and put back after the script is finished or crashed) to don't move around so much in throne, and just clear what is nessacary. I want to kill the monsters between certain coords, and not in a defined radius around the me object. This optimization just saves allot of time each run.

Anyway i'll adres to current issues with the thread, by either improving it so it has the use i originally had in mind, or remove it all together.

Thanks for reviewing the code in question =)

**Comment by Nishimura-Katsuo** [comment]
If you're overriding Attack.clear, calling it just for your script, and then putting it back, then it probably can just be a local function. Also, if you're looking for cross-script communication then you can use scriptBroadcast() or script.send(). If you're looking for communication between local characters you can leverage the new LocalChat option, and then respond to chat events. That should eliminate the need for threading at all and simplify the code a LOT. Maybe that will reduce the code and make it easier to follow :)

**Comment by noah-** [comment]
Please rebase and resubmit this PR.

**Pull request closed without merging**
