### PR TITLE
Javelin attack sequence

### PR DESCRIPTION
**Pull request by jaenster**
## Why?
Javelin bots suck, but if you play them by hand they are awesome. This PR aims to close the gap.

First of all, i saw that the LightningFuryDelay ruined everything for those chars. Because, it was throwing a javelin most of the time when only a single monster was available, and when you really wanted that the bot throw one, it was waiting for the timer.

Setting the timer to low, and you ran out of javelins. Specially on eth weapons, that was an issue. Since you cant do much more as wait.

## How
So what did i do? Its a bit hard to see since git sees the entire file as edited (the indentation moved).

I added a check if you wearing a javelin on your current weapon slot. If so, it calculates the best attack for that moment, that can be either an Lighting Fury, Lighting Strike (some cases its faster), or an Charged Strike.

The attack seq still keeps an fury timer, but one that automatically suits your (non)eth weapon. For maximum power. I tested this on mid-end and high-end javelin zon, and both do a dia run about 25% faster. (both had the same layout). I also tested this on a Tomb run, not only it ran faster, it also (surprisingly) used less furies, but also kept my mana on a higher lvl (which is a known problem) due to the fact it used effectively lighting strike from time to time.

## Other stuff 
- It might be important to note, that if you use this on a non-javelin char, it works just as before.
- You still need to setup the attack seq. Otherwise the koltons framework doesnt detects missing attack's and gives out warnings
    These are the settings i used.
    ```Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 24; // Primary skill to bosses.
	Config.AttackSkill[2] = 35; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 24; // Primary skill to others.
	Config.AttackSkill[4] = 35; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 10; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.```
	
- It might be beneficial to up the range where amazons can walk to, instead of teleporting, since the fcr breakpoints of the zon is so awful. (fastest fcr on an Amazon is still slower as a naked Sorc)
- I used a prototype that i added for #1523 . So if you merge this PR, you also merge the other one. If that one gets rejected, let me know so i make a new PR without #1523 embedded
- I removed the Config.LightningFuryDelay setting from the default Amazon config, as it isn't used anymore

### CODE REVIEW

**Comment by elobo91** [comment]
Hey man,  nice work there. im however having issue when using it 

attack.js  line 533  ClassAttack not defined

attack.js  line 182 	if (item.getPrefix(20566)) {    not defined 

prototypes.js line 141  referenceerror    Item not defined


amazon.js    missing :  after property id

can you help me?

**Comment by jaenster** [comment]
> 
> 
> Hey man, nice work there. im however having issue when using it
> 
> attack.js line 533 ClassAttack not defined
> 
> attack.js line 182 if (item.getPrefix(20566)) { not defined
> 
> prototypes.js line 141 referenceerror Item not defined
> 
> amazon.js missing : after property id
> 
> can you help me?

we resolved this together trough discord, as some files where copied wrong from github =)

No changes need to be commited

**Comment by jaenster** [comment]
resolved the merge conflicts

**Comment by jaenster** [comment]
I’ll close this for now. Will rewrite it in a more kolton styled way

**Pull request closed without merging**
