### PR TITLE
Replace 0xFF characters with escaped hex (\xFF)

### PR DESCRIPTION
**Pull request by szymski**
Characters for message coloring (0xFF) aren't recognized properly by some of the editors. This results in broken message coloring after modifying the files. By using \xFF sequence instead, this problem doesn't happen.

### CODE REVIEW

**Comment by noah-** [comment]
Can you make sure that the areas with .replace work properly and double check that the file encoding remained as ANSI in your commit? Also, would be great to get some across the board testing of various scripts to ensure there are no bugs introduced by this change. Apart from that, I think this is a good change and will accept the pull request upon completion of testing.

**Comment by noah-** [comment]
can someone test this change?

**Comment by noah-** [comment]
@mf2212 that pr was never merged

**Comment by jaenster** [comment]
Loving this. Would appreciate it =)

**Pull request merged**
