### PR TITLE
Add implementation of Config.ClearPath to bot scripts

### PR DESCRIPTION
**Pull request by jmichelsen**
This config var already exists but scripts weren't written to check the
var when traveling. Now they will clear while traveling, if Config.ClearPath is set to true

While traveling, chars that don't teleport often get blocked and end up exceeding the retry amount set and exiting the script with "failed to travel to x". Setting `Config.ClearPath = true;` will solve that sort of problem, as the bot will clear enemies blocking the path.

### CODE REVIEW

**Comment by 5noop** [comment]
Config.ClearPath is already implemented in NodeAction. However its usage is not documented (it needs a spectype mask or json object) so maybe there is something that could be done here.

**Comment by jmichelsen** [comment]
> Config.ClearPath is already implemented in NodeAction. However its usage is not documented (it needs a spectype mask or json object) so maybe there is something that could be done here.

Initially I added a new config var for this because I personally found it important to be able to control path clearing on a bot-by-bot basis, from a character config file as like I described in the pr, my bots that don't tele would get stuck.

Would it make more sense to change the variable used for this pr to a new one if `Config.ClearPath` is already _taken_, or are you saying the entire functionality in this pr already exists and I just missed it?

**Comment by 5noop** [comment]
> or are you saying the entire functionality in this pr already exists and I just missed it?

This, check NodeAction in Pather.js.

**Comment by jmichelsen** [comment]
Okay, I see what you're saying. Maybe I'll just add documentation around how to use this instead. Thanks

**Pull request closed without merging**
