### PR TITLE
Some fixes in ToolsThread

### PR DESCRIPTION
**Pull request by Legless**
1) Press Numpad 0 to precast;
2) Added additional stats to numpad+ output;

### CODE REVIEW

**Comment by Legless** [comment]
Fixed conflict with automap hotkey (numpad0 => move to next location).

(Idk how I forgot that.)

**Comment by IronMaXxX** [comment]
Thanks for your work Legless!

I added an overhead message to see which mule is logged without using the console, maybe you want to add this to your commit

```
case 102: // Numpad 6
   MuleLogger.logChar();
   me.overhead("logged char: " + (me.name));

break;
```

How can I add a new line to console?
I wanted to add some linefeeds to your new "show stats in console by pressinf num+" to make it more readable :)

**Comment by Legless** [comment]
@IronMaXxX 
> How can I add a new line to console?

```
showConsole(); // show console
print("This will be printed to console"); // print string to it
```

**Comment by Legless** [comment]
For some reason me.getStat(105) sometimes return absurd FCR values (like 300+).

**Comment by IronMaXxX** [comment]
@Legless ;)
I wanted to know how to add a line break to strings I want to print at console.

I think the shown fcr-values of 300+ are the real fcr from equipment + virtual fcr added by charconfig.
Not tried without +fcr from config.

**Comment by Legless** [comment]
@IronMaXxX 
> I wanted to know how to add a line break to strings I want to print at console.

Oh, sorry, I misunderstood you. You can either use multiple `print()` calls (each will output a new line) or use `\n` inside strings, ie: 

```
print( "line 1" );
print( "line 2" );
print( "line 3 \nline 4" );
```

And ofc `print()` will automatically wrap long strings to multiple lines.

> I think the shown fcr-values of 300+ are the real fcr from equipment + virtual fcr added by charconfig.
You're right, ty. <3 
I'll fix this.

**Comment by IronMaXxX** [comment]
IAS, FBR and FHR are also affected by charconfig.

Mind adding my suggested overhead to the mule log part?

**Comment by Legless** [comment]
@IronMaXxX Done.

**Comment by Legless** [comment]
Will add absorbs stats when I will have time.

**Pull request merged**
