### PR TITLE
Energy Shield precast with +es lvl items

### PR DESCRIPTION
**Pull request by mf2212**
**this was canceled** ... **fixed Cain ID then sell items**
Town.js fix for id at Cain and sell items
By default, identifying items at Cain will drop items if the requirements to keep aren't fulfilled.
In character configuration file, the value of this variable can be set to a lower limit, already in the toon's pocket.
Config.CainID.MinGold = xxx; // Minimum gold (stash + character) to have in order to use Cain.

### CODE REVIEW

**Comment by mf2212** [comment]
idk why the default Town.js has the UTF-8 encoding instead ANSI. I haven't changed that in this pull request.

What I have found before was that the scripts with UTF-8 encoding, won't show correctly the d2 colors for any **print** or **me.overhead** commands.

**Comment by noah-** [comment]
If you use the online uploader, it converts to utf-8. Also, regarding this pull request. This is actually not a bug. The reason Cain ID is not used is because it is slower than ID at NPC with scrolls. In the event, you are using cain, the only way it is faster is if you drop the items on the ground. Time to walk to NPC negates any benefit from cain ID. Also, gold is usually not an issue in this case, for certain scripts where gold is an issue, it can be implemented differently.

**Comment by mf2212** [comment]
I don't use the online uploader. I just checked the default file Town.js. In fact, first I have seen  the edited one, and my first thought was that my np++ changed that (it can do it if you set new document UTF-8).

this thing caused my a headache when I tested for Diabase a merged MuleLogger.js (which will save the log files both for Char Viewer, but for Diabase, too) the log files with unknown characters, caused only by UTF-8 encoding.

I have seen that download from pastebin.com will change the encoding to UTF-8 either.

About Cain, games in these days are not so fast on battle.net realms like in the past.

**Comment by mf2212** [comment]
it is analogous with enchant, checking the higher level of the Energy Shield skill on both weapon tab, before precasting it.

**Comment by noah-** [comment]
Can you separate this pull request from the cain id?

**Comment by mf2212** [comment]
I have cancelled the Cain changes, but I couldn't create a new pull request so it was merged here. The files changed are only those 2 related to Energy Shield

**Comment by mf2212** [comment]
@noah- I can make a new forked repo with only this atm, if what I have already said isn't enough.

**Comment by noah-** [comment]
You need to locally discard and only do the pull request on the affected changelist. I'll take a look maybe this weekend and resubmit it for you.

**Pull request closed without merging**
