### PR TITLE
Fixed SealLeecher/Leader

### PR DESCRIPTION
**Pull request by Legless**
Leechers will now end script after Diablo is killed.

### CODE REVIEW

**Comment by noah-** [comment]
You should use exit with leader. They should not exit on their own.

**Comment by Legless** [comment]
When I'm using SealLeecher and AutoBaal, all my leechers stays in Chaos Sanctuary after D is killed and leader goes to WSK/Throne. I couldnt find option for that. 

Did I missed something?

**Comment by noah-** [comment]
In your character config file:
```
Config.Leader = ""; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = [""]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 0; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).
```
Followers should use the QuitList

**Comment by Legless** [comment]
```
Config.Leader = "legless"; 
Config.QuitList = ["legless"]; 
Config.QuitListMode = 0; 
```

But this is not what I want. 

My leader have: 
```
...
Scripts.SealLeader = true;
...
Scripts.Baal = true;
...
```

Leechers: 
```
Scripts.SealLeecher = true;
...
Scripts.AutoBaal = true;
```

In game:
1. Leaders goes to CS, clears seals.
2. Leechers get exp.
3. Leader kills diablo and ends SealLeader, starts Baal script.
4. Leechers just stays at Chaos Sanctuary with SealLeecher script still active, 
5. Leader gooes to WSK, kills waves and Baal.
6. Leecher still stays in CS with SealLeecher script active.
7. Leaders quits game;
8. Leecher quits game.

zmttjoo

I looked into SealLeecher script and saw it just don't have any script end condition, so I made this fix to end script when leader says 'Diablo dead', so leechers will activate next script and not just standing still in CS.

**Comment by LeMule** [comment]
Ideally you want your bot to say nothing at all.
Previous release notes should have information on how to achieve this.

**Comment by noah-** [comment]
I understand your concern, change the command to "done" and I think your change is acceptable.

**Comment by Legless** [comment]
Done.

**Pull request merged**
