### PR TITLE
add pickItems before quit

### PR DESCRIPTION
**Pull request by cebor**
Give Followers the chance to pick items on the last boss sequence.

Fixes: https://github.com/kolton/d2bot-with-kolbot/issues/835

### CODE REVIEW

**Comment by noah-** [comment]
so some people mentioned this breaks a few scripts (like wakka) because pickit tries to make room so it goes to town etc, causing desync with leader

I will need to think about a more consistent way to do this

**Comment by cebor** [comment]
@noah- i moved the picket command to the point, where it scans the quitList. So it only will try to pick items, if its Profile which has set the QuitList and the Leader quits.

**Comment by imbalanced** [comment]
Profile running wakka could also have quitlist setup.
At this point, I think best approach is to have config option and set based on preference.

**Comment by noah-** [comment]
So why can't picking be added to the scripts directly where needed?

**Comment by cebor** [comment]
@noah- the problem is, that in some cases the leader quits before a follower had a chance to pick items.

Example:
Thw Follower has a cube recipe to build tokens from essences. If the Bot Team runs DiabloBaal, the Follower will pick only essences from Diablo cause the Leader directly quits after Baal dies.

**Comment by noah-** [comment]
Okay I can think of maybe 2 ways to fix this:
1) add a delay before quitting (like 3-5s) - however this might break some scripts
2) add some sort of variable "busy" where while (busy) { delay(100); } in toolsthread when it would be quitting, busy can be set by anything that wants to block toolsthread from exiting the game (via scriptmsg)

**Pull request closed without merging**
